// Prompts for Most Likely To. Each one finishes the sentence "Who is most likely to ...?"
// Keep them friendly: the fun is in the debate, not in embarrassing anyone.
window.LIKELY_PROMPTS = [
  "become famous", "forget their own birthday", "win a reality show", "survive a zombie apocalypse",
  "cry at a movie", "get lost in their own town", "adopt ten cats", "become a millionaire",
  "laugh at the wrong moment", "eat the last slice of pizza", "sleep through their alarm", "start a band",
  "talk their way out of trouble", "trip over nothing", "become president", "spend all their money on snacks",
  "go viral online", "fall asleep at a party", "win an eating contest", "live on a boat",
  "forget where they parked", "become a teacher", "adopt a weird pet", "be late to their own wedding",
  "join the circus", "watch a whole series in one day", "text the wrong person", "sing the loudest in the shower",
  "move to another country", "win the lottery and lose the ticket", "become an astronaut", "cook an amazing dinner",
  "burn toast", "give the best advice", "keep a secret forever", "spill a secret by accident",
  "know every word to every song", "talk to animals", "break a world record", "write a book",
  "dance on a table", "have the messiest room", "be the first to fall asleep", "stay up all night",
  "eat dessert first", "get scared by their own shadow", "win a staring contest", "become a superhero",
  "be a secret agent", "forget a name right after hearing it", "wear socks with sandals", "cry when they are happy",
  "snort when they laugh", "get stuck in an elevator", "lose their phone", "have a hundred tabs open",
  "start their own business", "know everyone at a party", "get lost in a big store", "argue with a referee",
  "become a TV chef", "run a marathon", "sleep until noon", "make friends with anyone",
  "bring snacks everywhere", "take a hundred selfies a day", "win a dance battle", "call their mom every day",
  "plan the perfect party", "forget to reply to a text", "laugh during a serious moment", "buy something useless at midnight",
  "believe in ghosts", "see a UFO", "become a YouTuber", "live to 100",
  "hide snacks in their room", "win any argument", "pretend to know a song", "go skydiving",
  "fix anything with tape", "eat something off the floor", "use a word wrong with total confidence", "get sunburned on a cloudy day",
  "be the last one ready", "show up early to everything", "have the best excuse", "lose their keys",
  "give the best hugs", "cheat at board games", "be a sore loser", "become a famous artist",
  "talk during a movie", "wave back at someone who was not waving at them", "eat cereal for dinner", "make up their own words",
  "have a secret talent", "cry at an ad", "win a talent show", "own the most shoes",
  "forget why they walked into a room", "sneeze the loudest", "become a detective", "survive alone in the wild",
  "get the giggles in class", "try a weird food first", "beat everyone at video games", "become a judge on a talent show",
  "text in all capital letters", "give their car a name", "have a jungle of house plants", "wake up first",
  "stay calm in an emergency", "panic over a spider", "become a famous chef", "go on an adventure at a moment's notice",
  "win a game show", "make everyone laugh", "get a pet llama", "drink coffee at midnight",
  "send a voice note instead of a text", "give a speech that makes everyone cry", "dress up for no reason", "remember everyone's birthday",
  "get caught singing in the car", "accidentally start a trend", "say yes to every dare", "eat the same lunch every day",
  "be the boss one day", "have a secret stash of chocolate", "become an inventor", "fall for a prank",
  "pull the best prank", "knit a sweater for their pet", "be the best at hide and seek", "name a star after themselves",
  "go back for seconds and thirds", "learn a new language for fun", "climb a mountain", "become a movie star",
  "talk in their sleep", "go to the wrong house", "laugh at their own jokes", "take the longest shower",
  "have the most embarrassing childhood photos", "write a love song", "befriend a celebrity", "keep every receipt",
  "end up on the news for something silly", "trip on stage", "cry over a sad book", "get the most likes"
];
