/* Questions for Flock. One plain string each.
   A good question has a couple of obvious answers and lots of possible ones,
   so the group can try to agree without talking. Keep them answerable by anyone. */
window.FLOCK_QUESTIONS = [
  "Name a pizza topping.",
  "Name a breakfast cereal.",
  "Name a yellow fruit.",
  "Name a cartoon character.",
  "Name something you take to the beach.",
  "What is the best day of the week?",
  "Name a farm animal.",
  "Name a breed of dog.",
  "Name a sport played with a ball.",
  "Name a vegetable people hate.",
  "Name a colour of the rainbow.",
  "Name a famous wizard.",
  "Name something you find in a kitchen drawer.",
  "Name a superhero.",
  "Name a board game.",
  "Name a chocolate bar.",
  "Name something people are scared of.",
  "Name a planet.",
  "Name a flavour of crisps.",
  "Name something you find in a classroom.",
  "Name a sandwich filling.",
  "Name a musical instrument.",
  "What is the best season of the year?",
  "Name a country in Europe.",
  "Name a job where you wear a uniform.",
  "Name a dessert.",
  "Name a reason for being late.",
  "Name a fast food chain.",
  "Name something with wheels.",
  "Name a type of weather.",
  "Name something you do every morning.",
  "Name a fairy tale character.",
  "Name a car brand.",
  "Name a sea creature.",
  "Name a popular name for a cat.",
  "Name a popular name for a dog.",
  "Name a hot drink.",
  "Name a holiday destination.",
  "Name something people collect.",
  "Name a word that rhymes with cat.",
  "Pick a number from 1 to 10.",
  "Name a shape.",
  "Name a household chore.",
  "Name a Christmas song.",
  "Name a flower.",
  "Name a bird.",
  "Name an insect.",
  "Name a type of shoe.",
  "Name a famous landmark.",
  "Name something you find in a bathroom.",
  "Name a flavour of ice cream.",
  "Name a cheese.",
  "Name a party game.",
  "Name a type of tree.",
  "Name something that flies.",
  "Name something that is round.",
  "Name a Disney film.",
  "Name a TV talent show.",
  "Name a big city.",
  "Name a type of bread.",
  "Name something people often lose.",
  "Name a famous scientist.",
  "Name a feeling.",
  "Name a vehicle that is not a car.",
  "Name something you wear on your head.",
  "Name a type of pasta.",
  "Name something sticky.",
  "Name a herb or spice.",
  "Name a superpower.",
  "Name a school subject.",
  "Name something people do on their phone.",
  "Name a sweet you loved as a kid.",
  "Name something you see at a wedding.",
  "Name a toy.",
  "Name a famous painter.",
  "Name a reptile.",
  "Name a type of nut.",
  "Name a breakfast food.",
  "Name a hobby.",
  "Name a dance.",
  "Name something that smells nice.",
  "Name something that smells bad.",
  "Name a playground game.",
  "Name a fizzy drink.",
  "Name something you find at a funfair.",
  "Name a room in a house.",
  "Name a piece of furniture.",
  "Name a gemstone.",
  "Name a metal.",
  "Name something you find in space.",
  "Name something in a first aid kit.",
  "Name a fish people eat.",
  "Name a famous detective.",
  "Name a monster.",
  "Name a magic word.",
  "Name something that keeps you awake at night.",
  "Name something you could not live without.",
  "Name something you do at the cinema.",
  "Name a sauce.",
  "Name an animal with stripes.",
  "Name an animal with spots.",
  "Name a jungle animal.",
  "Name an animal that lives somewhere cold.",
  "Name a type of cake.",
  "Name a pie filling.",
  "Name a soup.",
  "Name something you put in a salad.",
  "Name a type of hat.",
  "Name a famous bear.",
  "Name a famous mouse.",
  "Name a nursery rhyme.",
  "Name a song everyone knows the words to.",
  "Name a famous band.",
  "Name a kind of music.",
  "Name something you put on toast.",
  "Name something you take camping.",
  "Name something you do at a sleepover.",
  "Name a winter sport.",
  "Name something you do in summer.",
  "Name something green.",
  "Name something red.",
  "Name something blue.",
  "Name something purple.",
  "Name something you find in a handbag.",
  "Name a kitchen appliance.",
  "Name a tool in a toolbox.",
  "Name an Olympic sport.",
  "Name a famous footballer.",
  "Name a games console.",
  "Name a video game character.",
  "Name an app on your phone.",
  "Name a brand of trainers.",
  "Name a supermarket.",
  "Name something you buy at a petrol station.",
  "Name a famous king or queen.",
  "Name a film villain.",
  "Name something a pirate has.",
  "Name a dinosaur.",
  "Name a bug that bites.",
  "Name a word that means happy.",
  "Name a word that means big.",
  "Name something people do on a Sunday.",
  "What do you call your evening meal?",
  "Name the best biscuit to dunk in tea.",
  "What is the worst chore?",
  "Name the first thing you do when you wake up.",
  "Name the best animal.",
  "Name a famous duo.",
  "Name something that comes in pairs.",
  "Name something with a lid.",
  "Name something with buttons.",
  "Name something people queue for.",
  "Name something that goes up and down.",
  "Name something you plug in.",
  "Name a sound an animal makes.",
  "Name a fruit you peel.",
  "Name a vegetable that grows underground.",
  "Name a thing you find at the seaside.",
  "Name a reason to go to the doctor.",
  "Name a job that pays well.",
  "Name a job you would hate.",
  "Name a famous ghost or spooky place.",
  "Name a thing you do at a birthday party.",
  "Name a present everyone likes.",
  "Name a thing you see in the sky.",
  "Name a game you play with cards.",
  "Name a famous robot.",
  "Name a thing you keep in the fridge.",
  "Name a thing you keep in the freezer.",
  "Name a kind of sandwich.",
  "Name something you do when you are bored.",
  "Name a place you go on a school trip.",
  "Name something that is hot.",
  "Name something that is soft.",
  "Name something that is loud."
];
