// Opening lines for Story Chain. Silly, open-ended, and fine for all ages.
window.STORY_OPENERS = [
  "The day the cat learned to talk, the first thing it said was a complaint.",
  "Nobody expected the lunch lady to be a secret agent.",
  "When I opened the fridge, a tiny dragon looked back at me.",
  "The school bus took a wrong turn and ended up on the moon.",
  "Grandma's new hobby was skydiving.",
  "The pizza delivery came with a treasure map taped to the box.",
  "On the first day of summer, it started to snow.",
  "My shadow decided to go on vacation without me.",
  "The penguins at the zoo were planning an escape.",
  "Everyone in town woke up with the exact same haircut.",
  "The vending machine started giving out advice.",
  "A giant snail was blocking the highway.",
  "The dinosaur skeleton at the museum was missing on Monday morning.",
  "The teacher announced that homework was now against the law.",
  "My goldfish left me a note.",
  "The elevator had a button nobody had ever pressed.",
  "A unicorn moved in next door and it was very noisy.",
  "The rain started falling upwards.",
  "The new kid at school was a robot, and everyone knew it.",
  "Our camping trip was interrupted by a bear with a guitar.",
  "The birthday cake was alive.",
  "The library book was 300 years overdue.",
  "Every time I sneezed, it rained candy.",
  "The haunted house turned out to be very friendly.",
  "A pirate ship docked in the town swimming pool.",
  "The judge at the talent show was a llama.",
  "My socks were having a secret meeting.",
  "The alarm clock refused to wake anyone up.",
  "Santa got stuck in the wrong chimney.",
  "The ice cream truck played a song nobody had ever heard.",
  "A tiny door appeared in the kitchen wall.",
  "The moon sent the Earth a text message.",
  "Dad entered the family dog in a dance contest.",
  "The mall was empty except for one very large rabbit.",
  "A wizard tried to return a spell to the store.",
  "Our car could suddenly fly, but only backwards.",
  "The cafeteria served mystery soup, and the mystery was real.",
  "A time machine arrived in the mail.",
  "At midnight, the statue in the town square went for a walk.",
  "Aliens landed and asked for directions to the nearest pizza place.",
  "The vacation brochure did not mention the volcano.",
  "My reflection waved before I did.",
  "The soccer ball refused to go into the goal.",
  "Everyone's phone switched languages at the same time.",
  "A dog was elected mayor.",
  "The weather forecast said there was a chance of meatballs.",
  "The new teacher was very tall and very green.",
  "My backpack was much heavier than it should have been.",
  "We found a door at the bottom of the swimming pool.",
  "The superhero's cape got stuck in a revolving door."
];
