// Statements for Hot Takes. Harmless opinions that split a room.
window.HOT_TAKES = [
  "Pineapple belongs on pizza", "Cereal is a kind of soup", "A hot dog is a sandwich", "Cats are better than dogs",
  "Socks with sandals are fine", "Breakfast for dinner is the best dinner", "Summer is better than winter", "Ketchup on eggs is great",
  "Mornings are better than nights", "The book is always better than the movie", "Water is the best drink", "Chocolate ice cream beats vanilla",
  "Texting is better than calling", "Sleeping in is overrated", "Popcorn is the best movie snack", "Pancakes are better than waffles",
  "Toilet paper should hang over, not under", "Beach trips beat city trips", "Board games are more fun than video games", "Eating pizza with a knife and fork is fine",
  "Crunchy peanut butter beats smooth", "Rain is relaxing", "Cold pizza is better than hot pizza", "You should pour milk before cereal",
  "Naps are a waste of time", "Camping is fun", "Clowns are scary", "Mint chocolate tastes like toothpaste",
  "The middle seat gets both armrests", "Fruit does not count as dessert", "Sushi is overrated", "Musicals are fun",
  "Spicy food beats sweet food", "Everyone should learn to cook", "Pajamas all day on weekends is fine", "Dogs should be allowed in restaurants",
  "Snow days are the best days", "Leftovers taste better the next day", "Homework should be banned", "Everyone should have a pet",
  "Superhero movies are getting boring", "Coffee is overrated", "Tea is better than coffee", "Sweet popcorn beats salty popcorn",
  "Weekends should be three days long", "Reclining your seat on a plane is fine", "Mustard beats ketchup", "Hot chocolate is better than coffee",
  "Zoos are fun", "The best part of a cake is the frosting", "Ice cream is good in winter too", "Pickles are delicious",
  "Driving is better than flying for a trip", "Half birthdays should be celebrated", "Talking during a movie at home is rude", "You should make your bed every morning",
  "Showering at night beats showering in the morning", "Phones should be banned at the dinner table", "Chewing gum is annoying", "Socks should always match",
  "Cold weather is better than hot weather", "Bananas are the best fruit", "Apple pie is the best pie", "Spoons are better than forks",
  "Fireworks are overrated", "Video calls are better than phone calls", "Movie theaters beat watching at home", "Rollercoasters are fun",
  "A clean room is overrated", "Pizza crust is the best part", "Pets are family", "Grapes are better frozen",
  "The window seat is the best seat", "Dragons are cooler than unicorns", "Being early is the same as being on time", "Breakfast is the most important meal",
  "Aliens exist", "Ghosts are real", "Time travel would be a bad idea", "Flying is the best superpower",
  "Everyone should learn a second language", "Kids should stay up late on weekends", "Waking up early is a superpower", "Thin crust beats thick crust",
  "Broccoli is delicious", "Mashed potatoes beat fries", "Gift cards are a lazy gift", "Surprise parties are fun",
  "Karaoke is fun", "Eating dessert first is fine", "Dinner should be eaten at the table", "Swimming in the ocean beats a pool",
  "Hiking is fun", "Bugs are cool", "Puzzles are relaxing", "Cartoons are for all ages",
  "Animated movies beat live action", "Holiday decorations go up too early", "Holiday music in November is fine", "Gingerbread houses are for eating",
  "Snowmen beat sandcastles", "Reading the last page first is fine", "Pizza is the best food ever made", "Chocolate is better than candy",
  "Popcorn should be eaten one piece at a time", "Mondays are not that bad", "Weekdays are better than weekends", "Long car rides are fun",
  "The best seat at the movies is the back row", "Ketchup belongs in the fridge", "Sandwiches taste better cut in triangles", "Toast should be cut diagonally",
  "Hot dogs need ketchup", "Pancakes should be eaten with no syrup", "Soup is a dinner, not a lunch", "Salad can be a whole meal",
  "Popsicles beat ice cream", "Cupcakes beat cake", "Lemonade beats juice", "Bubble baths beat showers",
  "Slippers should be worn at home", "Shoes should come off inside", "Cats secretly love their owners", "Fish make great pets",
  "Everyone should know how to swim", "Singing in the shower is a must", "Dancing badly is better than not dancing", "Losing at games is fine",
  "Hide and seek is the best game", "Sleepovers are better than parties", "Birthdays matter more as you get older", "Cake should be eaten with a fork",
  "Hugging is better than a handshake", "The shower is the best place to think", "Rainy days are the coziest days", "Thunderstorms are exciting"
];
