// Secret words for Copycats. Everyday things anyone can give a one-word clue for.
window.COPYCAT_WORDS = [
  "Dog", "Cat", "Horse", "Elephant", "Giraffe", "Lion", "Penguin", "Shark", "Whale", "Octopus",
  "Spider", "Bee", "Butterfly", "Snake", "Frog", "Owl", "Monkey", "Kangaroo", "Turtle", "Rabbit",
  "Chicken", "Cow", "Pig", "Sheep", "Bear", "Panda", "Zebra", "Dolphin", "Crab", "Snail",
  "Bat", "Eagle", "Parrot", "Mouse", "Camel", "Fox", "Wolf", "Deer", "Squirrel", "Duck",
  "Pizza", "Banana", "Apple", "Chocolate", "Cheese", "Bread", "Egg", "Coffee", "Tea", "Milk",
  "Honey", "Popcorn", "Sandwich", "Soup", "Cake", "Cookie", "Ice cream", "Burger", "Pasta", "Rice",
  "Carrot", "Potato", "Tomato", "Lemon", "Orange", "Strawberry", "Watermelon", "Pineapple", "Candy", "Pancake",
  "Butter", "Salt", "Sugar", "Donut", "Pie", "Taco", "Sushi", "Grapes", "Peanut", "Mushroom",
  "Chair", "Table", "Bed", "Lamp", "Clock", "Mirror", "Window", "Door", "Key", "Phone",
  "Computer", "Camera", "Book", "Pencil", "Scissors", "Umbrella", "Glasses", "Watch", "Shoe", "Hat",
  "Sock", "Shirt", "Jacket", "Ring", "Necklace", "Backpack", "Suitcase", "Bottle", "Cup", "Spoon",
  "Fork", "Plate", "Candle", "Ball", "Kite", "Balloon", "Guitar", "Piano", "Drum", "Violin",
  "Trumpet", "Bicycle", "Car", "Bus", "Train", "Airplane", "Boat", "Rocket", "Helicopter", "Tractor",
  "Ladder", "Hammer", "Rope", "Bell", "Flag", "Map", "Coin", "Ticket", "Envelope", "Newspaper",
  "Magnet", "Battery", "Button", "Zipper", "Pillow", "Blanket", "Towel", "Soap", "Toothbrush", "Comb",
  "Broom", "Bucket", "Box", "Basket", "Crown", "Sword", "Shield", "Robot", "Dice", "Puzzle",
  "Sun", "Moon", "Star", "Cloud", "Rain", "Snow", "Wind", "Rainbow", "Lightning", "Volcano",
  "Mountain", "River", "Ocean", "Beach", "Island", "Forest", "Desert", "Cave", "Tree", "Flower",
  "Rose", "Leaf", "Grass", "Rock", "Sand", "Ice", "Fire", "Smoke", "Waterfall", "Tornado",
  "School", "Hospital", "Library", "Airport", "Castle", "Zoo", "Farm", "Park", "Museum", "Bank",
  "Prison", "Hotel", "Restaurant", "Kitchen", "Bathroom", "Garden", "Garage", "Stadium", "Circus", "Jungle",
  "Space", "City", "Bridge", "Tower", "Lighthouse", "Tent", "Igloo", "Supermarket", "Cinema", "Swimming pool",
  "Doctor", "Teacher", "Pilot", "Chef", "Police", "Firefighter", "Farmer", "King", "Queen", "Princess",
  "Pirate", "Ninja", "Wizard", "Witch", "Ghost", "Vampire", "Zombie", "Clown", "Magician", "Astronaut",
  "Baby", "Grandma", "Superhero", "Cowboy", "Knight", "Mermaid", "Dragon", "Unicorn", "Alien", "Angel",
  "Giant", "Birthday", "Wedding", "Christmas", "Halloween", "Vacation", "Party", "Dance", "Music", "Movie",
  "Soccer", "Tennis", "Swimming", "Camping", "Picnic", "Dream", "Sleep", "Shadow", "Secret", "Gift",
  "Treasure", "Letter", "Song", "Joke", "Smile", "Heart", "Brain", "Tooth", "Hair", "Nose",
  "Ear", "Eye", "Hand", "Foot", "Finger", "Skeleton", "Snowman", "Pumpkin", "Spaghetti", "Bubble",
  "Television", "Telescope", "Microscope", "Toothpaste", "Lipstick", "Perfume", "Wallet", "Diamond", "Gold", "Fireworks",
  "Rollercoaster", "Skateboard", "Snowboard", "Trampoline", "Sandcastle", "Treehouse", "Spaceship", "Submarine", "Parachute", "Compass",
  "Calendar", "Alarm", "Ghost story", "Haircut", "Homework", "Breakfast", "Weekend", "Winter", "Summer", "Autumn",
  "Spring", "Morning", "Night", "Thunder", "Puddle", "Mud", "Bone", "Nest", "Web", "Shell"
];
