/* Questions for Close Call. Each has a q (the question), an a (the exact answer as a number)
   and an optional u (the unit, shown with the answer). Answers must be facts with one
   clear number, so nobody can argue about the result. */
window.CLOSE_QUESTIONS = [
  { q: "How many keys are on a standard piano?", a: 88 },
  { q: "How many black keys are on a standard piano?", a: 36 },
  { q: "How many bones are in the adult human body?", a: 206 },
  { q: "In what year did the Titanic sink?", a: 1912 },
  { q: "How many squares are on a chessboard?", a: 64 },
  { q: "How many minutes are in a day?", a: 1440 },
  { q: "How many seconds are in an hour?", a: 3600 },
  { q: "How many seconds are in a day?", a: 86400 },
  { q: "How many states are in the USA?", a: 50 },
  { q: "How many countries are in the European Union?", a: 27 },
  { q: "How many teeth does an adult usually have, counting wisdom teeth?", a: 32 },
  { q: "How many hearts does an octopus have?", a: 3 },
  { q: "At what temperature in Fahrenheit does water boil at sea level?", a: 212, u: "degrees" },
  { q: "In what year did the Second World War end?", a: 1945 },
  { q: "In what year did people first walk on the Moon?", a: 1969 },
  { q: "How many people have walked on the Moon?", a: 12 },
  { q: "How many books are in the main Harry Potter series?", a: 7 },
  { q: "In what year was the first Harry Potter book published?", a: 1997 },
  { q: "In what year did the Berlin Wall fall?", a: 1989 },
  { q: "Roughly how many minutes does sunlight take to reach Earth?", a: 8, u: "minutes" },
  { q: "How tall is Mount Everest in metres?", a: 8849, u: "metres" },
  { q: "How many cards are in a standard deck, not counting jokers?", a: 52 },
  { q: "What do all the numbers on a six-sided die add up to?", a: 21 },
  { q: "How many stripes are on the flag of the USA?", a: 13 },
  { q: "In what year was the first iPhone released?", a: 2007 },
  { q: "In what year was Google founded?", a: 1998 },
  { q: "How many rings are on the Olympic flag?", a: 5 },
  { q: "In what year were the first modern Olympic Games held?", a: 1896 },
  { q: "How many players does a rugby union team have on the pitch?", a: 15 },
  { q: "How many holes are on a standard golf course?", a: 18 },
  { q: "What is the highest score you can get with three darts?", a: 180 },
  { q: "How many pieces does each player start with in chess?", a: 16 },
  { q: "How many squares are on a Scrabble board?", a: 225 },
  { q: "How many tiles are in an English Scrabble set?", a: 100 },
  { q: "How many dominoes are in a double-six set?", a: 28 },
  { q: "How many episodes of Friends were made?", a: 236 },
  { q: "How long is a marathon, to the nearest kilometre?", a: 42, u: "km" },
  { q: "How many metres are in a mile, to the nearest metre?", a: 1609, u: "metres" },
  { q: "How many grams are in a pound, to the nearest gram?", a: 454, u: "grams" },
  { q: "How many millilitres are in a UK pint, to the nearest millilitre?", a: 568, u: "ml" },
  { q: "How many eyes does a bee have?", a: 5 },
  { q: "How many legs does a lobster have, counting its claws?", a: 10 },
  { q: "In what year was the Eiffel Tower finished?", a: 1889 },
  { q: "In what year did the first Toy Story film come out?", a: 1995 },
  { q: "In what year was the first football World Cup played?", a: 1930 },
  { q: "How long is an Olympic swimming pool in metres?", a: 50, u: "metres" },
  { q: "How many countries are there in Africa?", a: 54 },
  { q: "How many teeth does an adult dog have?", a: 42 },
  { q: "How many hours are in a week?", a: 168 },
  { q: "How many sides does a 50p coin have?", a: 7 },
  { q: "In what year was the Great Fire of London?", a: 1666 },
  { q: "In what year was the Battle of Hastings?", a: 1066 },
  { q: "How many wives did Henry VIII have?", a: 6 },
  { q: "How many lines are in a sonnet?", a: 14 },
  { q: "How many players does a netball team have on court?", a: 7 },
  { q: "How many feet are in a mile?", a: 5280, u: "feet" },
  { q: "How tall is the London Eye in metres?", a: 135, u: "metres" },
  { q: "How tall is the Burj Khalifa in metres, to the nearest metre?", a: 828, u: "metres" },
  { q: "How many moons does Mars have?", a: 2 },
  { q: "For how many years was Elizabeth II queen, to the nearest year?", a: 70, u: "years" },
  { q: "How many minutes does a rugby union match last, not counting stoppages?", a: 80, u: "minutes" },
  { q: "How many tennis Grand Slam tournaments are played each year?", a: 4 },
  { q: "How many balls are in an over in cricket?", a: 6 },
  { q: "In what year did the Channel Tunnel open?", a: 1994 },
  { q: "How long is the Channel Tunnel, to the nearest kilometre?", a: 50, u: "km" },
  { q: "How many bones are in one human hand?", a: 27 },
  { q: "How many chambers does the human heart have?", a: 4 },
  { q: "How many Pokemon were in the very first Pokemon games?", a: 151 },
  { q: "How many coloured stickers are on a classic Rubik's Cube?", a: 54 },
  { q: "What is the highest break in snooker, without a free ball?", a: 147 },
  { q: "In what year did Super Mario Bros come out in Japan?", a: 1985 },
  { q: "In what year did Minecraft get its full release?", a: 2011 },
  { q: "On average, how far away is the Moon in kilometres, to the nearest thousand?", a: 384000, u: "km" },
  { q: "What is the speed limit on UK motorways in miles per hour?", a: 70, u: "mph" },
  { q: "How many points is a touchdown worth in American football?", a: 6 },
  { q: "How many minutes does a football match last, not counting stoppages?", a: 90, u: "minutes" },
  { q: "How many players does a basketball team have on court?", a: 5 },
  { q: "How many players does a volleyball team have on court?", a: 6 },
  { q: "How many days are in a leap year?", a: 366 },
  { q: "In what year did the Beatles release their first single, Love Me Do?", a: 1962 },
  { q: "How many symphonies did Beethoven finish?", a: 9 },
  { q: "How many old pennies were in a shilling?", a: 12 },
  { q: "How many time zones does Russia have?", a: 11 },
  { q: "How many official languages does Switzerland have?", a: 4 },
  { q: "How deep is the deepest point of the ocean in metres, to the nearest thousand?", a: 11000, u: "metres" },
  { q: "How many Oscars did the film Titanic win?", a: 11 },
  { q: "How many official James Bond films starred Sean Connery?", a: 6 },
  { q: "How many dalmatians are in the title of the Disney film?", a: 101 },
  { q: "In what year did Disneyland open in California?", a: 1955 },
  { q: "How many years of marriage is a golden anniversary?", a: 50, u: "years" },
  { q: "How many hours ahead of London is Tokyo in winter?", a: 9, u: "hours" },
  { q: "In what year did Tim Berners-Lee first propose the World Wide Web?", a: 1989 },
  { q: "How many chromosomes does a human usually have?", a: 46 },
  { q: "How many bones does a shark have?", a: 0 },
  { q: "In what year did the UK vote in the Brexit referendum?", a: 2016 },
  { q: "How many players does a cricket team have?", a: 11 },
  { q: "How many legs does a spider have?", a: 8 },
  { q: "How many years are in a millennium?", a: 1000 }
];
