// Question pairs for Odd One Out. Everyone gets one question, the odd one gets the other.
// type sets how people answer: fingers (0 to 10), point (at a player), hand (raise it or not), word (say one word).
window.ODD_PAIRS = [
  { type: "fingers", a: "How many hours of sleep do you need to feel good?", b: "How many hours a day do you spend on your phone?" },
  { type: "fingers", a: "Out of 10, how much do you like pizza?", b: "Out of 10, how much do you like broccoli?" },
  { type: "fingers", a: "How many cousins do you have?", b: "How many pets have you had in your life?" },
  { type: "fingers", a: "Out of 10, how good are you at singing?", b: "Out of 10, how good are you at dancing?" },
  { type: "fingers", a: "How many days a week do you eat breakfast?", b: "How many days a week do you exercise?" },
  { type: "fingers", a: "Out of 10, how scared are you of spiders?", b: "Out of 10, how scared are you of the dark?" },
  { type: "fingers", a: "How many countries have you visited?", b: "How many languages can you say hello in?" },
  { type: "fingers", a: "Out of 10, how much do you like mornings?", b: "Out of 10, how much do you like rainy days?" },
  { type: "fingers", a: "How many glasses of water do you drink a day?", b: "How many snacks do you eat a day?" },
  { type: "fingers", a: "Out of 10, how spicy do you like your food?", b: "Out of 10, how much do you like roller coasters?" },
  { type: "fingers", a: "How many siblings do you have?", b: "How many best friends do you have?" },
  { type: "fingers", a: "Out of 10, how messy is your room right now?", b: "Out of 10, how hungry are you right now?" },
  { type: "fingers", a: "How many times did you hit snooze this week?", b: "How many times did you eat pizza this month?" },
  { type: "fingers", a: "Out of 10, how good are you at keeping secrets?", b: "Out of 10, how good are you at cooking?" },
  { type: "fingers", a: "Out of 10, how much do you love the beach?", b: "Out of 10, how much do you love the snow?" },
  { type: "fingers", a: "How many pairs of shoes do you own?", b: "How many hats do you own?" },
  { type: "fingers", a: "Out of 10, how much do you like cats?", b: "Out of 10, how much do you like dogs?" },
  { type: "fingers", a: "How many times have you been to the movies this year?", b: "How many books have you read this year?" },
  { type: "fingers", a: "Out of 10, how good is your memory?", b: "Out of 10, how good is your sense of direction?" },
  { type: "fingers", a: "How many slices of pizza can you eat in one go?", b: "How many pancakes can you eat in one go?" },
  { type: "point", a: "Who here is the funniest?", b: "Who here is the loudest?" },
  { type: "point", a: "Who here would survive longest in the wild?", b: "Who here would win an eating contest?" },
  { type: "point", a: "Who here is the best cook?", b: "Who here is the best dancer?" },
  { type: "point", a: "Who here is most likely to become famous?", b: "Who here is most likely to sleep through an alarm?" },
  { type: "point", a: "Who here gives the best advice?", b: "Who here tells the best stories?" },
  { type: "point", a: "Who here would be the best teacher?", b: "Who here would be the best detective?" },
  { type: "point", a: "Who here is the most organized?", b: "Who here is the best at video games?" },
  { type: "point", a: "Who here would you call in an emergency?", b: "Who here would you take on a road trip?" },
  { type: "point", a: "Who here has the best laugh?", b: "Who here has the best style?" },
  { type: "point", a: "Who here is the best singer?", b: "Who here is worst at keeping a straight face?" },
  { type: "point", a: "Who here would win a staring contest?", b: "Who here would win a running race?" },
  { type: "point", a: "Who here is the most patient?", b: "Who here is the most competitive?" },
  { type: "point", a: "Who here would make the best superhero?", b: "Who here would make the best villain?" },
  { type: "point", a: "Who here is most likely to get lost?", b: "Who here is most likely to be late?" },
  { type: "point", a: "Who here gives the best gifts?", b: "Who here is best at hide and seek?" },
  { type: "hand", a: "Raise your hand if you have been on a plane.", b: "Raise your hand if you have been on a boat." },
  { type: "hand", a: "Raise your hand if you can whistle.", b: "Raise your hand if you can snap your fingers." },
  { type: "hand", a: "Raise your hand if you like pineapple on pizza.", b: "Raise your hand if you like olives." },
  { type: "hand", a: "Raise your hand if you have a pet.", b: "Raise your hand if you have a sibling." },
  { type: "hand", a: "Raise your hand if you can swim.", b: "Raise your hand if you can ride a bike." },
  { type: "hand", a: "Raise your hand if you are a morning person.", b: "Raise your hand if you love naps." },
  { type: "hand", a: "Raise your hand if you have ever broken a bone.", b: "Raise your hand if you have ever been in a hospital." },
  { type: "hand", a: "Raise your hand if you can cook pasta.", b: "Raise your hand if you can do a cartwheel." },
  { type: "hand", a: "Raise your hand if you sing in the shower.", b: "Raise your hand if you talk to animals." },
  { type: "hand", a: "Raise your hand if you have seen snow.", b: "Raise your hand if you have seen the ocean." },
  { type: "hand", a: "Raise your hand if you prefer summer to winter.", b: "Raise your hand if you prefer cake to pie." },
  { type: "hand", a: "Raise your hand if you like scary movies.", b: "Raise your hand if you like roller coasters." },
  { type: "hand", a: "Raise your hand if you have a nickname.", b: "Raise your hand if you have a middle name." },
  { type: "hand", a: "Raise your hand if you can touch your toes.", b: "Raise your hand if you can wiggle your ears." },
  { type: "hand", a: "Raise your hand if you have ever won a trophy.", b: "Raise your hand if you have ever been on stage." },
  { type: "word", a: "Name a fruit.", b: "Name a vegetable." },
  { type: "word", a: "Name a pizza topping.", b: "Name a sandwich filling." },
  { type: "word", a: "Name an animal at the zoo.", b: "Name an animal on a farm." },
  { type: "word", a: "Name a color of the rainbow.", b: "Name a color on a traffic light." },
  { type: "word", a: "Name a sport with a ball.", b: "Name a sport in the Olympics." },
  { type: "word", a: "Name a breakfast food.", b: "Name a dessert." },
  { type: "word", a: "Name something in a kitchen.", b: "Name something in a bathroom." },
  { type: "word", a: "Name a superhero.", b: "Name a cartoon character." },
  { type: "word", a: "Name a great vacation spot.", b: "Name a place you never want to visit." },
  { type: "word", a: "Name a hot drink.", b: "Name a cold drink." },
  { type: "word", a: "Name something cold.", b: "Name something white." },
  { type: "word", a: "Name a job.", b: "Name a job you would hate." },
  { type: "word", a: "Name a day of the week.", b: "Name a month." },
  { type: "word", a: "Name a musical instrument.", b: "Name something that makes noise." },
  { type: "word", a: "Name something with wheels.", b: "Name something that flies." },
  { type: "word", a: "Name a famous movie.", b: "Name a famous song." },
  { type: "word", a: "Name a board game.", b: "Name a card game." },
  { type: "word", a: "Name an ice cream flavor.", b: "Name a candy." },
  { type: "word", a: "Name a body part.", b: "Name something you wear." },
  { type: "word", a: "Name a word that rhymes with cat.", b: "Name a word that rhymes with dog." }
];
