// Starting prompts for Doodle Chain. Funny, drawable, and clear without any special knowledge.
window.DOODLE_PROMPTS = [
  "A cat riding a skateboard", "A snowman at the beach", "A dog wearing sunglasses", "A pizza with legs",
  "A dragon eating spaghetti", "A shark in a bathtub", "A robot walking a dog", "A giraffe in an elevator",
  "A monkey playing drums", "A cow on the moon", "A penguin on vacation", "A sandwich that is way too tall",
  "A superhero doing laundry", "Grandma on a rollercoaster", "A pirate ship in the desert", "A snail winning a race",
  "An octopus playing guitar", "A banana driving a car", "A volcano made of ice cream", "A ghost brushing its teeth",
  "A tiny elephant in a teacup", "A fish riding a bicycle", "A unicorn at the dentist", "A wizard stuck in traffic",
  "A dinosaur at a birthday party", "A bear going fishing", "A cactus giving a hug", "A dog flying a kite",
  "Aliens at the supermarket", "A chicken crossing the road", "A frog wearing a crown", "A hamster in a hamster ball",
  "A cat napping in a shoe", "A bird building a house", "A camel in the snow", "A horse eating spaghetti",
  "A clown juggling eggs", "A vampire at the beach", "A knight fighting a teddy bear", "A mermaid on a bike",
  "A spider knitting a sweater", "A lion getting a haircut", "A mouse stealing cheese", "A baby running a marathon",
  "A turtle on a skateboard", "A sloth at the gym", "A panda snowboarding", "A hot air balloon over the sea",
  "A burger with too much cheese", "A rainbow in a jar", "A dog in outer space", "A tree house in a storm",
  "A cowboy riding a chicken", "A UFO taking a cow", "A broken umbrella in the rain", "A sleepy sun",
  "A melting snowman", "A selfie with a bear", "A dog doing homework", "Someone stepping on a Lego",
  "A pig in a puddle", "A runaway shopping cart", "A ninja eating sushi", "A birthday cake on fire",
  "A picnic full of ants", "An astronaut riding a horse", "A crab holding scissors", "A kangaroo with a backpack",
  "A pumpkin with a face", "A giant cupcake", "A dinosaur eating a tree", "A worm reading a book",
  "A train going through a tunnel", "A crocodile at the dentist", "A lighthouse in a storm", "Pizza delivery by rocket",
  "A king with a tiny crown", "A grumpy cloud", "A happy toaster", "A sock monster",
  "A moose in a canoe", "A fox in a winter hat", "A parrot talking on the phone", "A dog chasing its tail",
  "A rabbit pulling a magician out of a hat", "A skeleton dancing", "A bat hanging upside down", "An owl wearing glasses",
  "A dragon blowing out birthday candles", "A shark with braces", "A flamingo standing on one leg", "A goldfish in a huge bowl",
  "A whale spraying water", "A haunted toilet", "A tent with bears outside", "A tiny castle on a cloud",
  "A cat stuck in a tree", "A kid flying away with balloons", "A traffic jam of snails", "A giraffe wearing a scarf",
  "A volcano erupting popcorn", "A dog in a bubble bath", "The moon made of cheese", "A melting clock",
  "A monkey eating a banana split", "A goat on a mountain top", "A hedgehog hugging a balloon", "A polar bear in the desert",
  "A chicken breathing fire", "A tiny house on a turtle", "A piano falling from the sky", "A spaceship made of cardboard",
  "A crying onion", "An angry carrot", "The sun wearing sunglasses", "A cat being a DJ",
  "A dog walking a person", "A potato on a couch", "A robot making pancakes", "A penguin ice skating",
  "A zebra with polka dots", "A cow jumping over the moon", "An alien taking a selfie", "A worm with a mustache",
  "A pig with wings", "A snowman with a sunburn", "A ladybug holding an umbrella", "A bee wearing a helmet",
  "Twins on a tandem bike", "A soccer ball with a face", "A sad ice cream cone", "A bear on a unicycle",
  "A cupcake wearing a party hat", "A mummy at the beach", "A dog wearing a tie at the office", "A goldfish driving a submarine",
  "A teacher with eyes on the back of her head", "A lion brushing its mane", "A banana slipping on a person", "A sheep counting people"
];
