/* Words for Spy Grid. Short, common words that can mean more than one thing work best,
   because they let clue givers link several words at once. Keep each word to 7 letters
   or fewer so it fits a small square on a phone. */
window.SPY_WORDS = [
  "Anchor", "Angel", "Apple", "Arm", "Arrow", "Bacon", "Badge", "Ball", "Band", "Bank",
  "Bar", "Bark", "Bat", "Battery", "Beach", "Beam", "Bean", "Bear", "Bed", "Bee",
  "Bell", "Belt", "Bench", "Berry", "Bike", "Bill", "Bird", "Blade", "Block", "Board",
  "Boat", "Bolt", "Bomb", "Bone", "Book", "Boot", "Bottle", "Bow", "Bowl", "Box",
  "Brain", "Branch", "Brick", "Bridge", "Brush", "Bubble", "Bucket", "Bug", "Bulb", "Bull",
  "Bus", "Butter", "Button", "Cab", "Cable", "Cake", "Camel", "Camera", "Camp", "Candle",
  "Cap", "Car", "Card", "Carpet", "Carrot", "Castle", "Cat", "Cell", "Chain", "Chair",
  "Chalk", "Change", "Charge", "Check", "Cheese", "Chest", "Chick", "Chip", "Circle", "Cliff",
  "Clock", "Cloud", "Club", "Coach", "Coat", "Code", "Coin", "Cold", "Comb", "Comet",
  "Cone", "Cook", "Copper", "Coral", "Cord", "Corn", "Cotton", "Court", "Cow", "Crab",
  "Crane", "Crash", "Cream", "Crown", "Cube", "Cup", "Curry", "Cycle", "Dance", "Date",
  "Deck", "Desk", "Diamond", "Dice", "Dinner", "Disc", "Doctor", "Dog", "Doll", "Dolphin",
  "Door", "Dragon", "Drain", "Dream", "Dress", "Drill", "Drink", "Drop", "Drum", "Duck",
  "Eagle", "Ear", "Egg", "Engine", "Eye", "Face", "Fair", "Fall", "Fan", "Farm",
  "Feather", "Fence", "Field", "File", "Film", "Fire", "Fish", "Flag", "Flame", "Flash",
  "Flour", "Flower", "Flute", "Fly", "Fog", "Foot", "Fork", "Fox", "Frame", "Frog",
  "Frost", "Fruit", "Game", "Garden", "Gas", "Ghost", "Giant", "Gift", "Glass", "Glove",
  "Glue", "Goal", "Gold", "Grape", "Grass", "Ground", "Guitar", "Gum", "Hair", "Ham",
  "Hammer", "Hand", "Hat", "Hawk", "Head", "Heart", "Helmet", "Hero", "Hole", "Honey",
  "Hook", "Horn", "Horse", "Hose", "Hotel", "House", "Ice", "Ink", "Iron", "Island",
  "Jacket", "Jam", "Jar", "Jet", "Jewel", "Judge", "Juice", "Jump", "Kettle", "Key",
  "King", "Kite", "Knife", "Knight", "Knot", "Ladder", "Lake", "Lamp", "Lap", "Laser",
  "Lead", "Leaf", "Leg", "Lemon", "Letter", "Light", "Lime", "Line", "Lion", "Lip",
  "Lock", "Log", "Loop", "Magic", "Mail", "Map", "Marble", "March", "Mask", "Match",
  "Meat", "Medal", "Melon", "Metal", "Milk", "Mine", "Mint", "Mirror", "Model", "Money",
  "Monkey", "Moon", "Moth", "Motor", "Mouse", "Mouth", "Mud", "Mug", "Music", "Nail",
  "Needle", "Nest", "Net", "Night", "Ninja", "Note", "Nurse", "Nut", "Oak", "Ocean",
  "Octopus", "Oil", "Onion", "Orange", "Organ", "Owl", "Page", "Paint", "Palm", "Pan",
  "Panda", "Paper", "Park", "Party", "Pass", "Paste", "Peach", "Pear", "Pearl", "Pen",
  "Pencil", "Pepper", "Piano", "Pie", "Pig", "Pilot", "Pin", "Pipe", "Pirate", "Pit",
  "Pizza", "Plane", "Plant", "Plate", "Play", "Plug", "Pocket", "Point", "Pole", "Police",
  "Pool", "Port", "Post", "Pot", "Potato", "Press", "Prince", "Pump", "Puzzle", "Queen",
  "Rabbit", "Race", "Radio", "Rain", "Ram", "Ray", "Record", "Ring", "River", "Road",
  "Robot", "Rock", "Rocket", "Roll", "Roof", "Root", "Rope", "Rose", "Ruler", "Salt",
  "Sand", "Satchel", "Saw", "Scale", "School", "Screen", "Seal", "Seat", "Shadow", "Shark",
  "Sheep", "Shell", "Ship", "Shirt", "Shoe", "Shop", "Shot", "Sign", "Silk", "Sink",
  "Skate", "Ski", "Sky", "Slip", "Smoke", "Snake", "Snow", "Soap", "Sock", "Soup",
  "Space", "Spell", "Spice", "Spider", "Spike", "Spine", "Sponge", "Spoon", "Spot", "Spring",
  "Square", "Stage", "Stamp", "Star", "Steam", "Stick", "Stone", "Storm", "Straw", "String",
  "Suit", "Sugar", "Sun", "Swan", "Sweet", "Swing", "Sword", "Table", "Tail", "Tank",
  "Tap", "Tea", "Tent", "Thread", "Throne", "Ticket", "Tie", "Tiger", "Toast", "Toe",
  "Tooth", "Torch", "Tower", "Toy", "Track", "Train", "Trap", "Tree", "Trip", "Truck",
  "Trunk", "Tube", "Tune", "Turkey", "Turtle", "Tyre", "Unicorn", "Van", "Vase", "Violin",
  "Wall", "Wand", "Watch", "Water", "Wave", "Web", "Whale", "Wheel", "Whip", "Whistle",
  "Wind", "Window", "Wing", "Wire", "Witch", "Wolf", "Wood", "Wool", "Worm", "Yard",
  "Yarn", "Yolk", "Zebra", "Zip"
];
