// Locations for Where Are We? Each place has roles handed out to everyone except the spy.
window.WAW_PLACES = [
  { name: "Airplane", roles: ["Pilot", "Flight attendant", "Passenger in first class", "Passenger in the middle seat", "Parent with a crying baby", "Air marshal", "Nervous flyer"] },
  { name: "Hospital", roles: ["Surgeon", "Nurse", "Patient", "Visitor", "Night shift doctor", "Janitor", "Receptionist"] },
  { name: "School", roles: ["Teacher", "Principal", "Student", "Lunch server", "Janitor", "Substitute teacher", "School nurse"] },
  { name: "Beach", roles: ["Lifeguard", "Surfer", "Sunbather", "Ice cream seller", "Kid building a sandcastle", "Tourist", "Photographer"] },
  { name: "Restaurant", roles: ["Chef", "Waiter", "Customer", "Food critic", "Dishwasher", "Host", "Musician"] },
  { name: "Supermarket", roles: ["Cashier", "Shopper", "Security guard", "Shelf stacker", "Butcher", "Manager", "Kid in the cart"] },
  { name: "Movie theater", roles: ["Ticket seller", "Projectionist", "Movie fan", "Popcorn seller", "Couple on a date", "Usher", "Cleaner"] },
  { name: "Zoo", roles: ["Zookeeper", "Vet", "Tourist", "Kid on a school trip", "Ticket seller", "Photographer", "Lion"] },
  { name: "Hotel", roles: ["Receptionist", "Guest", "Bellhop", "Housekeeper", "Chef", "Manager", "Doorman"] },
  { name: "Space station", roles: ["Astronaut", "Commander", "Scientist", "Engineer", "Alien visitor", "Doctor", "Space tourist"] },
  { name: "Pirate ship", roles: ["Captain", "Sailor", "Cook", "Prisoner", "Lookout", "Parrot", "Treasure hunter"] },
  { name: "Bank", roles: ["Teller", "Manager", "Customer", "Security guard", "Robber", "Accountant", "Cleaner"] },
  { name: "Police station", roles: ["Detective", "Officer", "Suspect", "Lawyer", "Witness", "Police chief", "Reporter"] },
  { name: "Circus", roles: ["Clown", "Acrobat", "Ringmaster", "Lion tamer", "Juggler", "Audience member", "Magician"] },
  { name: "Farm", roles: ["Farmer", "Farmhand", "Vet", "Tractor driver", "Visitor", "Kid feeding the animals", "Scarecrow"] },
  { name: "Ski resort", roles: ["Ski instructor", "Snowboarder", "Beginner skier", "Lift operator", "Rescue patrol", "Hot chocolate seller", "Tourist"] },
  { name: "Cruise ship", roles: ["Captain", "Tourist", "Waiter", "Musician", "Lifeguard", "Chef", "Cabin cleaner"] },
  { name: "Amusement park", roles: ["Ride operator", "Mascot", "Thrill seeker", "Parent", "Kid", "Food seller", "Photographer"] },
  { name: "Library", roles: ["Librarian", "Student", "Author", "Book lover", "Security guard", "Kid at story time", "Cleaner"] },
  { name: "Museum", roles: ["Tour guide", "Security guard", "Tourist", "Art student", "Painter", "Curator", "School kid"] },
  { name: "Train", roles: ["Conductor", "Driver", "Passenger", "Ticket inspector", "Snack cart seller", "Commuter", "Tourist"] },
  { name: "Wedding", roles: ["Bride", "Groom", "Best man", "Flower girl", "Photographer", "Guest", "DJ"] },
  { name: "Birthday party", roles: ["Birthday kid", "Parent", "Clown", "Guest", "Magician", "Cake maker", "Grandparent"] },
  { name: "Gym", roles: ["Personal trainer", "Bodybuilder", "Yoga teacher", "Beginner", "Receptionist", "Runner", "Cleaner"] },
  { name: "Hair salon", roles: ["Hairdresser", "Customer", "Receptionist", "Nail artist", "Apprentice", "Chatty client", "Barber"] },
  { name: "Camping trip", roles: ["Camp leader", "Camper", "Park ranger", "Kid", "Fisher", "Hiker", "Camp cook"] },
  { name: "Fire station", roles: ["Firefighter", "Fire chief", "Rookie", "Dispatcher", "Station dog", "Visitor", "Mechanic"] },
  { name: "Castle", roles: ["King", "Queen", "Knight", "Jester", "Cook", "Guard", "Princess"] },
  { name: "Submarine", roles: ["Captain", "Sonar operator", "Cook", "Engineer", "Navigator", "Scientist", "Sailor"] },
  { name: "Concert", roles: ["Singer", "Drummer", "Fan", "Security guard", "Sound engineer", "Merch seller", "Photographer"] },
  { name: "Stadium", roles: ["Player", "Coach", "Referee", "Fan", "Commentator", "Mascot", "Hot dog seller"] },
  { name: "Haunted house", roles: ["Ghost", "Tour guide", "Scared visitor", "Ghost hunter", "Owner", "Brave kid", "Caretaker"] },
  { name: "Airport", roles: ["Pilot", "Security officer", "Traveler", "Check-in agent", "Baggage handler", "Shop clerk", "Late passenger"] },
  { name: "Aquarium", roles: ["Diver", "Guide", "Shark", "Visitor", "Kid", "Vet", "Ticket seller"] },
  { name: "Car wash", roles: ["Washer", "Customer", "Manager", "Kid in the back seat", "Dog in the car", "Cashier", "Delivery driver"] },
  { name: "Dentist's office", roles: ["Dentist", "Patient", "Assistant", "Receptionist", "Nervous kid", "Parent", "Cleaner"] }
];
