// Spectrum cards for Tune In. Each card is [left end, right end].
// Good cards have a fuzzy middle that people will argue about.
window.TUNE_CARDS = [
  ["Cold", "Hot"],
  ["Useless", "Useful"],
  ["Bad habit", "Good habit"],
  ["Underrated", "Overrated"],
  ["Easy to spell", "Hard to spell"],
  ["Smells bad", "Smells good"],
  ["Bad pizza topping", "Good pizza topping"],
  ["Normal pet", "Weird pet"],
  ["Forgettable", "Unforgettable"],
  ["Unhealthy food", "Healthy food"],
  ["Cheap", "Expensive"],
  ["Quiet", "Loud"],
  ["Boring hobby", "Fun hobby"],
  ["Kid food", "Grown-up food"],
  ["Easy job", "Hard job"],
  ["Soft", "Hard"],
  ["Tiny", "Huge"],
  ["Slow", "Fast"],
  ["Not scary", "Terrifying"],
  ["Harmless animal", "Dangerous animal"],
  ["Bad movie snack", "Good movie snack"],
  ["Terrible gift", "Perfect gift"],
  ["Easy to draw", "Hard to draw"],
  ["Rare", "Common"],
  ["Old-fashioned", "Modern"],
  ["Lame superpower", "Amazing superpower"],
  ["Sad song", "Happy song"],
  ["Bad breakfast", "Great breakfast"],
  ["Low effort", "High effort"],
  ["Sweet", "Salty"],
  ["Light", "Heavy"],
  ["Dry", "Wet"],
  ["Mild", "Spicy"],
  ["Safe", "Dangerous"],
  ["Indoor activity", "Outdoor activity"],
  ["Easy to make", "Hard to make"],
  ["Gone in a day", "Lasts forever"],
  ["Bad party guest", "Great party guest"],
  ["A bit annoying", "Extremely annoying"],
  ["Tiny problem", "Huge problem"],
  ["Unpopular opinion", "Popular opinion"],
  ["Overpriced", "Worth every penny"],
  ["Needs no talent", "Needs real talent"],
  ["Bad first date", "Great first date"],
  ["Bad pet name", "Great pet name"],
  ["Snack", "Meal"],
  ["Feels like summer", "Feels like winter"],
  ["Lazy", "Hardworking"],
  ["Childish", "Mature"],
  ["Messy", "Tidy"],
  ["Normal", "Weird"],
  ["Useless invention", "Life-changing invention"],
  ["Not a sport", "Definitely a sport"],
  ["Not a sandwich", "Definitely a sandwich"],
  ["Not a vegetable", "Definitely a vegetable"],
  ["Rude", "Polite"],
  ["Unlucky", "Lucky"],
  ["Fragile", "Sturdy"],
  ["Bad hiding spot", "Great hiding spot"],
  ["Plain", "Fancy"],
  ["Sleepy", "Full of energy"],
  ["Bad advice", "Good advice"],
  ["Worst holiday", "Best holiday"],
  ["Comfortable", "Uncomfortable"],
  ["Cheap date", "Expensive date"],
  ["Cute monster", "Scary monster"],
  ["Weak", "Strong"],
  ["Easy to remember", "Hard to remember"],
  ["Low tech", "High tech"],
  ["Smooth", "Rough"],
  ["Dull color", "Bright color"],
  ["Tastes bad", "Tastes good"],
  ["Bad for the planet", "Good for the planet"],
  ["No manual needed", "Needs a manual"],
  ["Basic skill", "Advanced skill"],
  ["Worst chore", "Best chore"],
  ["Bad road trip snack", "Good road trip snack"],
  ["Waste of time", "Good use of time"],
  ["Kids hate it", "Kids love it"],
  ["Normal thing to collect", "Weird thing to collect"],
  ["Casual", "Formal"],
  ["Peaceful", "Chaotic"],
  ["Not cool", "Very cool"],
  ["Ancient", "Brand new"],
  ["Easy to carry", "Hard to carry"],
  ["Silly", "Serious"],
  ["Boring", "Exciting"],
  ["Bad gift for a teacher", "Good gift for a teacher"],
  ["Unbelievable", "Believable"],
  ["Sticky", "Slippery"],
  ["Bad karaoke song", "Great karaoke song"],
  ["Easy to say no to", "Impossible to say no to"],
  ["Embarrassing", "Impressive"],
  ["Rarely used", "Used every day"],
  ["Morning thing", "Night thing"],
  ["Clean", "Dirty"],
  ["Natural", "Artificial"],
  ["Boring zoo animal", "Exciting zoo animal"],
  ["Unknown", "Famous"],
  ["Breakfast food", "Dinner food"],
  ["Bad costume", "Great costume"],
  ["Useless room", "Most important room"],
  ["Bad thing to find in your pocket", "Good thing to find in your pocket"],
  ["Cats love it", "Cats hate it"],
  ["Dogs love it", "Dogs hate it"],
  ["Grandma would hate it", "Grandma would love it"],
  ["No flavor", "Strong flavor"],
  ["Short", "Tall"],
  ["Easy to explain", "Hard to explain"],
  ["Bad mascot", "Great mascot"],
  ["Over in a flash", "Feels like forever"],
  ["Not funny", "Hilarious"],
  ["Plain food", "Fancy food"],
  ["Hard to find", "Easy to find"],
  ["Goes in the fridge", "Goes in the cupboard"],
  ["Optional", "Essential"],
  ["Worst fruit", "Best fruit"],
  ["Worst ice cream flavor", "Best ice cream flavor"],
  ["Easy to fake", "Hard to fake"],
  ["Bad thing to bring camping", "Good thing to bring camping"],
  ["Bad excuse", "Good excuse"],
  ["Normal to say to a stranger", "Weird to say to a stranger"],
  ["Common skill", "Rare skill"],
  ["Bad first job", "Great first job"],
  ["Villain", "Hero"],
  ["Bad candle scent", "Good candle scent"],
  ["Sounds made up", "Sounds real"],
  ["Ugly", "Beautiful"],
  ["Bad Halloween candy", "Good Halloween candy"],
  ["Loved by everyone", "Hated by everyone"],
  ["Easy to learn", "Hard to learn"],
  ["Small talk topic", "Deep talk topic"],
  ["Overrated movie", "Underrated movie"],
  ["Smells like home", "Smells like a hospital"],
  ["Bad sandwich filling", "Good sandwich filling"],
  ["Worst smell", "Best smell"],
  ["Calm", "Stressful"],
  ["Sounds fancy", "Sounds cheap"],
  ["Bad name for a boat", "Good name for a boat"],
  ["Mildly useful", "Can't live without it"],
  ["Hard to sleep through", "Easy to sleep through"],
  ["Fun to say", "Awkward to say"],
  ["Underground", "In the sky"],
  ["Basic", "Extra"],
  ["Free", "Costs a fortune"],
  ["Tastes healthy", "Tastes like dessert"],
  ["Bad superhero name", "Good superhero name"],
  ["Worst place to nap", "Best place to nap"],
  ["Square", "Round"],
  ["Real", "Fake"],
  ["Thing you share", "Thing you never share"],
  ["Overrated sport", "Underrated sport"],
  ["Bad day", "Great day"],
  ["Most likely to break", "Least likely to break"],
  ["Weird food combo", "Perfect food combo"],
  ["Gross", "Delicious"],
  ["Good at parties", "Bad at parties"],
  ["Popular baby name", "Unusual baby name"],
  ["Bad song for a wedding", "Good song for a wedding"],
  ["Feels like Monday", "Feels like Friday"],
  ["Easy question", "Hard question"],
  ["Worth the wait", "Not worth the wait"],
  ["Cozy", "Uncomfortable"],
  ["Hated in school", "Loved in school"]
];
