// Strange but true facts for Fake Facts. Each fact has one blank (___) and its real answer.
window.FAKE_FACTS = [
  { q: "A group of flamingos is called a ___.", a: "flamboyance" },
  { q: "A baby kangaroo is called a ___.", a: "joey" },
  { q: "The national animal of Scotland is the ___.", a: "unicorn" },
  { q: "An octopus has ___ hearts.", a: "three" },
  { q: "A shrimp's heart is in its ___.", a: "head" },
  { q: "Scientifically speaking, a banana is a type of ___.", a: "berry" },
  { q: "The dot over a lowercase i is called a ___.", a: "tittle" },
  { q: "A group of crows is called a ___.", a: "murder" },
  { q: "Wombats make poop shaped like ___.", a: "cubes" },
  { q: "On Venus, a single day lasts longer than a ___.", a: "year" },
  { q: "Sea otters hold ___ while they sleep so they do not drift apart.", a: "hands" },
  { q: "The man who designed the Pringles can was buried in a ___.", a: "Pringles can" },
  { q: "A group of owls is called a ___.", a: "parliament" },
  { q: "Butterflies taste things with their ___.", a: "feet" },
  { q: "Goats have pupils shaped like ___.", a: "rectangles" },
  { q: "Peanuts are not really nuts. They are ___.", a: "legumes" },
  { q: "In Switzerland, it is illegal to own just one ___.", a: "guinea pig" },
  { q: "A jiffy is a real unit of ___.", a: "time" },
  { q: "Koalas can sleep up to ___ hours a day.", a: "22" },
  { q: "Under their white fur, polar bears have ___ skin.", a: "black" },
  { q: "A group of porcupines is called a ___.", a: "prickle" },
  { q: "In summer heat, the Eiffel Tower grows about ___ centimeters taller.", a: "15" },
  { q: "In colonial America, lobster was seen as cheap food fit for ___.", a: "prisoners" },
  { q: "Apples float in water because they are about one quarter ___.", a: "air" },
  { q: "A group of jellyfish is called a ___.", a: "smack" },
  { q: "Bubble wrap was first invented to be used as ___.", a: "wallpaper" },
  { q: "The first item ever scanned with a barcode at a checkout was a pack of ___.", a: "gum" },
  { q: "Kangaroos cannot easily walk ___.", a: "backwards" },
  { q: "An ostrich's eye is bigger than its ___.", a: "brain" },
  { q: "Cleopatra lived closer in time to the Moon landing than to the building of the ___.", a: "Great Pyramid" },
  { q: "When Nintendo started in 1889, it made ___.", a: "playing cards" },
  { q: "Oxford University is older than the ___ Empire.", a: "Aztec" },
  { q: "A big fluffy cloud can weigh as much as 100 ___.", a: "elephants" },
  { q: "Honeybees can learn to recognize human ___.", a: "faces" },
  { q: "A group of ferrets is called a ___.", a: "business" },
  { q: "In the 1830s, ketchup was sold as ___.", a: "medicine" },
  { q: "The shortest war in history lasted about ___ minutes.", a: "38" },
  { q: "Rats make a laughing sound when they are ___.", a: "tickled" },
  { q: "Before it was called Google, the search engine was called ___.", a: "BackRub" },
  { q: "Dolphins sleep with one ___ open.", a: "eye" },
  { q: "Koala fingerprints are so close to ___ fingerprints that they could confuse a detective.", a: "human" },
  { q: "There are more possible games of chess than there are ___ in the observable universe.", a: "atoms" },
  { q: "Some penguins win over a partner by giving them a ___.", a: "pebble" },
  { q: "The microwave oven was invented after a scientist noticed a ___ had melted in his pocket.", a: "chocolate bar" },
  { q: "Avocados used to be called ___ pears.", a: "alligator" },
  { q: "The plastic tip on the end of a shoelace is called an ___.", a: "aglet" },
  { q: "Sharks have existed longer than ___.", a: "trees" },
  { q: "There is an island in Japan overrun with friendly ___.", a: "rabbits" },
  { q: "A group of zebras is called a ___.", a: "dazzle" },
  { q: "The first farmed carrots were not orange. They were ___.", a: "purple" },
  { q: "The Mona Lisa has no ___.", a: "eyebrows" },
  { q: "Tigers do not just have striped fur. They also have striped ___.", a: "skin" },
  { q: "A baby puffin is called a ___.", a: "puffling" },
  { q: "The official state sport of Maryland is ___.", a: "jousting" },
  { q: "Astronauts can grow up to 2 inches taller in ___.", a: "space" },
  { q: "The longest recorded flight by a chicken lasted ___ seconds.", a: "13" },
  { q: "A woodpecker's ___ wraps around its skull.", a: "tongue" },
  { q: "On the top floor of the US Supreme Court building there is a ___.", a: "basketball court" },
  { q: "Researchers found that the Scots language has over 400 words for ___.", a: "snow" },
  { q: "One of the first alarm clocks could only ring at ___ in the morning.", a: "4" },
  { q: "A newborn panda is about the size of a stick of ___.", a: "butter" },
  { q: "Cotton candy was co-invented by a ___.", a: "dentist" },
  { q: "Some lipsticks get their shimmer from fish ___.", a: "scales" },
  { q: "The giant squid has the biggest ___ of any animal.", a: "eyes" },
  { q: "Honeybees ___ to tell each other where the flowers are.", a: "dance" },
  { q: "A newborn baby has more ___ than an adult.", a: "bones" },
  { q: "Venus spins the opposite way to most planets, so there the sun rises in the ___.", a: "west" },
  { q: "The pineapple and ham pizza known as Hawaiian was invented in ___.", a: "Canada" },
  { q: "An average strawberry has about ___ seeds on the outside.", a: "200" },
  { q: "A group of hippos is called a ___.", a: "bloat" },
  { q: "In the Middle Ages, a moment was a unit of time lasting about ___ seconds.", a: "90" },
  { q: "A hummingbird's heart can beat more than ___ times a minute.", a: "1200" },
  { q: "The longest common English word with no a, e, i, o or u is ___.", a: "rhythm" },
  { q: "A pineapple plant takes about ___ years to grow a single pineapple.", a: "two" },
  { q: "Adult elephants cannot ___.", a: "jump" }
];
