/* Prompts for Punchline. Players finish each one with something funny, and the judge
   picks a favourite. Keep them family friendly, so the game works at any table. */
window.PUNCH_PROMPTS = [
  "The worst thing to hear from your pilot",
  "A terrible name for a pet goldfish",
  "What the dog is really thinking",
  "The secret ingredient in Grandma's famous soup",
  "A bad thing to say in a job interview",
  "The most useless superpower",
  "A rejected flavour of crisps",
  "What aliens think humans do all day",
  "The title of your life story",
  "A new rule for every school",
  "The worst present to give a teacher",
  "What the cat does when nobody is home",
  "A terrible slogan for a dentist",
  "The real reason the dinosaurs disappeared",
  "A bad name for a boat",
  "The worst thing to find in your sandwich",
  "What your phone would say if it could talk",
  "A strange thing to keep in the fridge",
  "The worst theme for a birthday party",
  "A brand new Olympic sport",
  "A terrible name for a band",
  "The worst flavour of ice cream",
  "A bad excuse for not doing your homework",
  "The worst thing to shout in a library",
  "A rejected name for a chocolate bar",
  "The most useless invention ever",
  "A rubbish superhero name",
  "What really happens at a sleepover",
  "A terrible advert for a holiday",
  "The worst ride at a theme park",
  "What pigeons talk about",
  "A job robots will never be able to do",
  "The worst way to start a wedding speech",
  "What is really at the bottom of the sea",
  "A spooky thing to find in the attic",
  "The worst thing to say to a wizard",
  "What your goldfish dreams about",
  "A bad name for a racehorse",
  "The real reason the chicken crossed the road",
  "A new flavour of toothpaste",
  "Something you should never say to a ghost",
  "The worst thing to bring to a picnic",
  "A rejected Christmas song",
  "What the Moon thinks about all night",
  "The worst sound to hear in the middle of the night",
  "A terrible name for a restaurant",
  "The worst thing to put on a pizza",
  "What snowmen do in the summer",
  "A bad thing to write in a birthday card",
  "The worst job in a castle",
  "A terrible thing to hear from your hairdresser",
  "The first thing you would do if you were invisible",
  "A very bad nickname for a teacher",
  "Something you would never want to win in a raffle",
  "The worst way to wake someone up",
  "A pirate's least favourite thing",
  "What a cow would say if it could talk",
  "The worst thing a satnav could say",
  "A terrible name for a perfume",
  "The worst superhero sidekick",
  "A new law that everyone has to follow",
  "What happens to socks that go missing",
  "A bad thing to say on a first day at work",
  "The worst thing to find under your bed",
  "The worst way to spend a million pounds",
  "A rejected name for a new planet",
  "What a penguin keeps in its pocket",
  "The worst prize on a game show",
  "A terrible motto for a family",
  "A sign you are not a very good cook",
  "The worst sport to watch on TV",
  "A new reality TV show nobody asked for",
  "What babies are really thinking",
  "The worst thing to hear at the dentist",
  "Something you should never order at a cafe",
  "A bad name for a dragon",
  "A weird thing to collect",
  "The real reason your teacher is always tired",
  "The worst thing to say when meeting the King",
  "A terrible name for a hotel",
  "What a tree would complain about",
  "A rejected fairy tale",
  "The worst hobby to have on a train",
  "What the Tooth Fairy does with all the teeth",
  "A strange thing to see at the supermarket",
  "The worst thing to lose on holiday",
  "A sign that your house is haunted",
  "A terrible name for a hamster",
  "What would happen if cats ruled the world",
  "The worst new smell for a candle",
  "A bad name for a robot",
  "The worst way to end a fairy tale",
  "Something a vampire would buy in a shop",
  "The worst thing to bring to a sleepover",
  "A reason to cancel a football match",
  "A job that should exist but does not",
  "The worst thing about being a superhero",
  "A terrible ice cream van tune",
  "The worst thing to say to a lion",
  "What your shadow does when you are asleep",
  "A bad name for a wifi network",
  "A terrible thing to hear on the school tannoy",
  "The worst gift for a newborn baby",
  "What a seagull would steal first",
  "The worst way to cook an egg",
  "A new thing to put on toast",
  "The worst film to watch on a plane",
  "A rejected name for a theme park",
  "What a shark worries about",
  "The worst thing to do at a museum",
  "Something you would find in a giant's pocket",
  "The worst thing to say in a group chat",
  "A terrible new sandwich",
  "What dogs say about humans behind their backs",
  "A bad thing to hear from your doctor",
  "The worst thing to put in a time capsule",
  "A new holiday everyone should celebrate",
  "The worst thing to forget on a school trip",
  "A rejected name for a dog food",
  "What the Easter Bunny does the rest of the year"
];
